### ISSUE TITLE
Реализация подсказок по типам зарядки на карте станций

### ISSUE THREAD

**Issue by haritonasty** [haritonasty/itmo-engineering#15]

**Comment by haritonasty** [comment]
v14

**Comment by haritonasty** [comment]
версия станет доступна в 10:20 20.11.17

**Comment by Integraali10** [comment]
реализация протестирована. все отображается. Тестирование проводилось в версии v14

**Comment by haritonasty** [comment]
поправит пути

**Comment by haritonasty** [comment]
добавить более мягкую поддержку добавления пинов на карту

**Comment by haritonasty** [comment]
добавлена  удобная CMS  для добавления пинов на карту

**Comment by haritonasty** [comment]
v16

**Comment by Integraali10** [comment]
Функционал проверен, соответствует сценарию в чеклисте. Версия 16
